version: '2'

services:

    app:
        build:
            args:
                guid: ${APP_GUID}
                hostname: ${APP_HOSTNAME}
                uid: ${APP_UID}
            context: ./docker/app
        links:
            - db
        ports:
            - 443:443
        volumes:
            - ./:/var/www/html

    db:
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}

        image: mysql
        ports:
            - 3306:3306
        volumes:
            - ./data/db:/var/lib/mysql
